### ISSUE TITLE
upgrading from A9LH to B9S exception on first luma start

### ISSUE THREAD

**Issue by Konoa** [d0k3/SafeSigHaxInstaller#10]
ive put all the files in the right places but when i execute start_safeb9sinstaller, i get "An exception occured" arm9 data dump and then press start to shutdown

**Comment by d0k3** [comment]
Format this SD card fresh or try with a different one. Then let me know if it worked for you.

**Comment by Konoa** [comment]
If I do that. Do I just copy all the files back or redo all of a9lh over again. I'm not very savvy with this stuff

**Comment by d0k3** [comment]
Just copy all the files back.

**Comment by shag04** [comment]
i am having this same issue and i have tried multiple sd cards 1 of which i went out and bought brand new, i have been trying everything i can think of but i always get a data abort

**Comment by Konoa** [comment]
I just formatted the micro sd and then copied my back up files back onto it. Then I redone loaded all the boot9strap installation files all over again and double checked putting them in the right folders as the 3ds.guide said and it finally worked

**Comment by shag04** [comment]
I've tried that, over and over again on multiple sd cards,even formatted system memory and sd cards again, my a9lh and everything works fine but every time i try to update to boot9strap i get a data abort still, much help would be greatly appreciated.

**Comment by Konoa** [comment]
What all is in your luma/payloads folder?

**Comment by shag04** [comment]
the payloads folder the config file and the dumps folder with the crash logs in it

**Comment by d0k3** [comment]
Can you try this test build?
https://transfer.sh/Dhisa/SafeB9SInstaller-20170531-223541.zip

Maybe that helps. If not, use SafeB9SInstaller as arm9loaderhax_si.bin (remove the arm9loaderhax.bin before you try that), or use it from the Luma chainloader if you didn't do so before.

**Comment by shag04** [comment]
IT WORKED, renaming to arm9loaderhax_si.bin finally got it to launch successfully.  Thank you so much.

**Comment by d0k3** [comment]
Good to hear :).
