### ISSUE TITLE
FIRM crypto fail

### ISSUE THREAD

**Issue by 7starsuperman** [d0k3/SafeSigHaxInstaller#11]
Ok so I used the .bin as a safehaxpayload instead of the .3dsx which just booted me back to menuhax but now when it's open I get "SigHaxed FIRM was not installed!" on the top screen, and "Crypto status - FIRM crypto fail" on the bottom screen. I'm running a SysNAND that was downgraded to 9.2 via ctrNAND transfer. Help, any ideas?

**Comment by d0k3** [comment]
Try the latest hourly from here:
https://d0k3.secretalgorithm.com/

Problem fixed?

**Comment by 7starsuperman** [comment]
Yeah, thanks!

**Comment by d0k3** [comment]
Worked?

**Comment by 7starsuperman** [comment]
Yup, I transferred my EmuNAND via Godmode9 (thanks for making that) and got
B9S (thanks for making that) running nicely with Luma. Thanks!
