### ISSUE TITLE
Support for b9s 1.1. 

### ISSUE THREAD

**Issue by jupitteer** [d0k3/SafeSigHaxInstaller#13]
I upgraded to b9s 1.1, which was a mistake. Running any payloads, including safeb9sinstaller, crashes. I really need to downgrade.

**Comment by Carbuino** [comment]
Download this modified B9S installer https://transfer.sh/bi8b5/SafeB9SInstaller.firm and upgrade to v1.2

**Comment by Shadow322** [comment]
thanks for saving my ass

**Comment by d0k3** [comment]
Solved with latest​ release

**Comment by vitordiniz22** [comment]
Where can I find this modified B9S installer?

**Comment by ihaveamac** [comment]
latest release should work fine with all b9s releases.
