### ISSUE TITLE
A9LH TO B9S issue

### ISSUE THREAD

**Issue by david-zzj** [d0k3/SafeSigHaxInstaller#14]
i have done a9lh to b9s,it display succeed.
but when i reboot ,the o3ds power blue light	immediately off，likes there is no boot.firm in the SD.
but i am sure i have place the LUMA v8.0 in the SD root.

**Comment by james-d-elliott** [comment]
Download Luma 8.0 again and Luma 7.1 again. Try once with the boot.firm from 7.1 then 8.0. Luma 8.0 is only supported by B9S 1.2 which you may not have installed, so if Luma 7.1 works then you need to upgrade here https://3ds.guide/updating-b9s 

GitHub is for bugs with software not support though. If this does not fix it you can get support on Discord: https://discord.gg/C29hYvh

**Comment by david-zzj** [comment]
thank you very much！！
Luma 7.1 is work.
i should update to B9S 1.2 and Luma 8.0,right ?

**Comment by james-d-elliott** [comment]
It is recommended, it's much better. Feel free to close the issue since it's solved.

**Comment by david-zzj** [comment]
ok, thx
