### ISSUE TITLE
Would it be possible to add a way to uninstall B9S?

### ISSUE THREAD

**Issue by TheNain38** [d0k3/SafeSigHaxInstaller#17]
To avoid people from uninstalling it by error, I think it could be enabled with a flag in the compilation, and you could also add a security sequence to be entered, like it does on Godmode9, and it could also check if the console can be hacked back in software based on the current version of the System.

**Comment by d0k3** [comment]
Although strictly not recommended (for reasons other than making it genuine for sending in again), this is already available as gm9 script. Look inside the GM9 issues, FIRM0/1 restoring.
