### ISSUE TITLE
now the bak is two  how can turn in to  one 

### ISSUE THREAD

**Issue by 7690362** [d0k3/SafeSigHaxInstaller#18]
hi!
now the bak is two  how can i turn in to  one for the hardmod? thamk you

**Comment by james-d-elliott** [comment]
You don't need to, it uses firm1_enc.bak and firm0_enc.bak by default. 

https://github.com/ihaveamac/hardmod-b9s-installer/blob/master/restore-firm0firm1.py#L23-L32

https://github.com/ihaveamac/hardmod-b9s-installer/blob/master/restore-firm0firm1.py#L46-L50

**Comment by d0k3** [comment]
As an additional note - I seriously don't get why you guys like restoring these backups that much, when nothing ever went wrong installing boot9strap, but w/e...

Use the newest hourly of GodMode9 and one of these scripts:

//(to restore the backups (that's what you like to do)
https://transfer.sh/V8bmr/revert_sb9si.gm9 

// to get back to unhaxed state
https://transfer.sh/9yuB8/uninstall_hax_retail_n3ds.gm9
https://transfer.sh/iLzVv/uninstall_hax_retail_o3ds.gm9
