### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by Jan200101** [d0k3/SafeSigHaxInstaller#2]
I've followed 3ds.guide to update a9lh to b9s.
Starting the updater resulted in
![20170520_083032](https://cloud.githubusercontent.com/assets/15076013/26273781/29bf14f4-3d38-11e7-9697-40d9e43a3922.jpg)

I've tried redownloading every file, no success

Here is the Crash Dump
[crash_dump_00000000.dmp.zip](https://github.com/d0k3/SafeB9SInstaller/files/1015971/crash_dump_00000000.dmp.zip)

I'm on 11.4 using a old EU device.
DVSCold has reported that its also happening on a new 3ds

**Comment by d0k3** [comment]
You're the only one who has this happening that I know of. Is anything special about your 3DS? Can you try the most recent nightly from here and tell me the result?
https://d0k3.secretalgorithm.com/

**Comment by Jan200101** [comment]
I haven't install anything subnormal and installed cfw 2 weeks ago
I'm going to test the beta build now

**Comment by Jan200101** [comment]
Still the same

**Comment by Jan200101** [comment]
It's not region specific or based on new or old 3ds thats as far as I could get

**Comment by d0k3** [comment]
Okay, can you try this one?
https://transfer.sh/1Fcf5/SafeB9SInstaller-20170520-133818.zip

If it crashes again, can you give me again a screenshot and the crash dump? Make sure everything is visible on that screenshot.

**Comment by Jan200101** [comment]
Again uploading the files you were requesting right now.
Could it be that my Luma version is bugging the installer somehow?

**Comment by Jan200101** [comment]
![20170520_162242](https://cloud.githubusercontent.com/assets/15076013/26276500/f94b59cc-3d78-11e7-9e69-da74930e0d95.jpg)
![20170520_162253](https://cloud.githubusercontent.com/assets/15076013/26276502/009c885e-3d79-11e7-8cd3-941ecc0cc335.jpg)
[crash_dump_00000007.dmp.zip](https://github.com/d0k3/SafeB9SInstaller/files/1016230/crash_dump_00000007.dmp.zip)

**Comment by Jan200101** [comment]
Woops wrong button

**Comment by Jan200101** [comment]
Okay I have switched between 2 SD cards and tried the payloads.
On one it randomly worked, I think it was the newest one... 
so when it doubt switch sd card.... weird

**Comment by urherenow** [comment]
Is the other SD card 64k clusters or gpt instead of primary mbr?

**Comment by Jan200101** [comment]
Both SD Cards had a 64k cluster and both were primary mbr.
The only difference was the size

**Comment by urherenow** [comment]
They should be 32k cluster though. Yout lucky either of them worked at all.

**Comment by d0k3** [comment]
GM9 allows to format with 64k clusters, too, that's not the issue here. It's something else.

**Comment by DVSCold** [comment]
I'm the other user that Jan200101 is talking about, I tried formatting my SD card to the 32k cluster as it was on 64k and don't have access to another SD card at the moment. It still gives me a crash/dump each time regardless. If I find the old N3DS SD can I put the files onto it, upgrade it and then switch back to my sd card?

Firmware: 11.4E
Model: N3DSXL
SD Card: Sandisk Ultra Class 10 64gb

**Comment by insanedude63** [comment]
This issue is happening on my N3DS as well.... maybe the issue is not closed. I use a 32GB SD though.

**Comment by d0k3** [comment]
Do what those other guys did, use another SD card or format this one in GodMode9.

**Comment by Jan200101** [comment]
Infos for others:
 - I couldnt update on my 32GB sd card (Size allocation 64k)
 - I could update on my 4 GB sd card (Size allocation 64k)

**Comment by shag04** [comment]
so i'm having this same issue but not only with SafeB9SInstaller but also when i launch GodMode9 i get the exact same error, im still trying to locate a new sd card to test on but felt like i should share that this error is happening on multiple apps for me

**Comment by Jhynjhiruu** [comment]
I don't even reach SafeB9SInstaller any more - the Luma3DS Chainloader crashes now. But SafeB9SInstaller was crashing with an ARM9 data abort for me.

**Comment by d0k3** [comment]
You did only update boot9strap, but forgot about updating Luma / GM9 / SafeB9SInstaller.
