### ISSUE TITLE
Data abort

### ISSUE THREAD

**Issue by eros71-dev** [d0k3/SafeSigHaxInstaller#20]
Sorry im writing from a phone so i cant copy paste right now
Heres an image of the error
Thanks for helping!
Top screen:
http://imgur.com/a/ASPd0
Bottom screen:
http://imgur.com/a/cAh5V

**Comment by d0k3** [comment]
I somehow missed that issue. Did you figure out how to make it work yet?

**Comment by eros71-dev** [comment]
I dont know ,the last thing I did is lend my 3ds to a friend and he could use it,the magic of the 3ds homebrew! I was like : WOWOWOWWOWO when i saw that it worked for him.

**Comment by eros71-dev** [comment]
And thanks for helping!
