### ISSUE TITLE
Micro SD card init failed

### ISSUE THREAD

**Issue by eruandou** [d0k3/SafeSigHaxInstaller#22]
I'm trying to bring back a new 3ds which has been bricked for the last 5 months. I'm using magnethax to boot up safeb9sinstaller. Even though it boots Up Fine, it states an error concerning the micro SD. I've tried multiple sd cards, changed the microSD reader on the console but nothing seems to solve the problem. Any ideas as to where to look at to try and solve it?

**Comment by Derek1199** [comment]
What did you do to brick? Like how did you brick? I need to know how so I can help you.

**Comment by eruandou** [comment]
The console was bricked by injecting a bad nand backup  (corrupted because of a faulty sd card) through hardmod  (after the original user tried to change secureinfoA FULLY while on sysnand having a menuhax+emunand setup, so this would the original brick cause)

**Comment by Derek1199** [comment]
Was it someone hexediting all the bytes on your Secureinfo_A?

**Comment by eruandou** [comment]
It's not my 3ds tho. But yes, the user hexedited his secureinfoA file and that gave him a black screen on startup.

**Comment by Derek1199** [comment]
You would likely need to hexedit the bytes back to normal then. Although that would be very difficult. As its almost impossible to know what was changed. Hmmm. Ask @d0k3 then.

**Comment by eruandou** [comment]
Now I'm thinking about booting decrypt9 as boot.firm and try to see if changing it back to the code on the back shell of the 3ds works

**Comment by Derek1199** [comment]
Try AutofixCTRNand on decrypt9.

**Comment by eruandou** [comment]
Same issue comes around...fails to initialize sd card :/

**Comment by Derek1199** [comment]
Do you have the files9 folder then? Add the support files to the files9 folder. Shouldn't really be needed, but if it does it should help.

**Comment by eruandou** [comment]
Only one I can actually access is godmode9. Should I go for a ctrnandtransfer from here?

**Comment by Derek1199** [comment]
Yeah. Try a clean image.

**Comment by Derek1199** [comment]
Also you might have a fake SD card or a faulty one. I would suggest you try using h2testw on it.

**Comment by eruandou** [comment]
No Luck either. Even though it lets me select the ctrnand image, and click on "transfer image to ctrnand" it just kicks me back as if I had pressed B.  I've run out of ideas

**Comment by Derek1199** [comment]
Try running h2testw on your SD card to check for bad sectors. Also how big is your SD card or supposed to be?

**Comment by d0k3** [comment]
Try this:
https://github.com/AnalogMan151/Lazarus3DS

Remember, GitHub issues is not for support. If you need further help using this script ask in the usual places.

Also, what @Derek1199 said. I wouldn't use that SD card anymore without a thorough check.

Also, closing this now, cause obvious SD card issue. Feel free to reopen if you think / can prove I'm wrong.
