### ISSUE TITLE
Compatibility with boot9straps v1.3

### ISSUE THREAD

**Issue by 1mcuadros** [d0k3/SafeSigHaxInstaller#24]
Compatibility with boot9straps v1.3.
Thanks.

**Comment by Committee** [comment]
Isn't it already compatible? All paths in 3ds.guide point to getting the latest relase of boot9strap and the latest release of SafeB9SInstaller.

**Comment by d0k3** [comment]
Have you even tried tried installing boot9strap v1.3? :/.
