### ISSUE TITLE
[Issue / Suggestion] Alternate Key combo ?

### ISSUE THREAD

**Issue by RichardPaulAstley** [d0k3/SafeSigHaxInstaller#25]
Hi !

I'm having a issue with the tool. My friend asked me to install B9S for his 3DS, and I saw that the up button of the D-Pad was broken. So no way to complete the key combo. 

I guess it could be nice to have a version with the key combo with the d-pad and one with the stick or something like that.

Thank you !

**Comment by d0k3** [comment]
And here's to another broken button request...

Possibility #1: fix that console.
Possibility #2: remove the unlock sequence code and compile yourself. Or find someone who can.

Unlock code is here:
https://github.com/d0k3/SafeB9SInstaller/blob/6c493ac132fa39c7e97307f5eff1b1c81118ce46/source/installer.c#L204-L213

And, if I'd even start doing alternative versions for people who have x (insert button / screen / whatever) broken on their console I'd never even get to do any real development work. So, you're on your own for this, but the info above will help you.
