### ISSUE TITLE
compatibility (1.3)

### ISSUE THREAD

**Issue by greaperkam** [d0k3/SafeSigHaxInstaller#26]
is this compatible with bootstrap 1.3?

**Comment by urherenow** [comment]
Huh? All this does is install to firm0. It's "compatible" with anything that's intended to go there.

**Comment by d0k3** [comment]
Yes, any boot9strap version can chainload this. And it can install any boot9strap version.

GitHub issues is not for support though, but rather for bug reports and feature requests.
