### ISSUE TITLE
Cant boot to safe9

### ISSUE THREAD

**Issue by K0D1M** [d0k3/SafeSigHaxInstaller#30]
I am doing the 3ds guide for the boot9stap upgrade and when i press start to boot safe9 it boots to godmode9

**Comment by d0k3** [comment]
This isn't for support. Ask this on GBAtemp, on an IRC channel or on some other support forum. GitHub issues is for bug reports and feature requests only.

Hint: you can also try rereading the guide to find where you went wrong.
