### ISSUE TITLE
suggestion: Adding a poweroff option.

### ISSUE THREAD

**Issue by Altairseven** [d0k3/SafeSigHaxInstaller#31]
Right now, after installing boot9strap using ntrboot,  you have to forcefully poweroff the device in order to change the boot.firm payload

it would be nice to have a power off option.

**Comment by urherenow** [comment]
Been posted and answered before. This has nothing to do with safeB9Sinstaller. You want an ntr version of boot9strap that looks for ntrboot.firm flashed to your DS cart. Then safeB9Sinstaller will be ntrboot.firm while luma is boot.firm.

**Comment by jason0597** [comment]
https://github.com/d0k3/SafeB9SInstaller/issues/27

**Comment by d0k3** [comment]
Adding the wontfix label here, cause I'll only do that if someone does a pull request for that other open issue. This on it's own does not warrant a release.

@urherenow is right, too. A version of b9s loading `ntrboot.firm` is preferred. Also, you can help yourself by just leaving your 3DS on while you remove the SD card and do the required modifications.

**Comment by Altairseven** [comment]
@urherenow is not dangerous to remove the sd while the installer is on stand by?

**Comment by d0k3** [comment]
Not at this point... SafeB9SInstaller does no writing to the SD card, so there are no caches that might not be written yet, and all the writing to the NAND is already finished at that time. It is an unelegant solution, though.

**Comment by Altairseven** [comment]
yes it is unelegant, but it will do, thanx
