### ISSUE TITLE
Add screen init to SafeB9SInstaller(.bin)

### ISSUE THREAD

**Issue by jason0597** [d0k3/SafeSigHaxInstaller#32]
Currently it is impossible to use SafeB9SInstaller.bin as your arm9loaderhax.bin boot payload, due to the fact that it has no screen init built in. You are forced to chainload it through something like luma 7.0.5

You also cannot rename it to `arm9loaderhax_si.bin` due to the fact that some users are running such old installations of A9LH that do not have such a feature.

This is so that you can speed up the [a9lh-to-b9s](https://3ds.guide/a9lh-to-b9s) guide. If users were instead to use SafeB9SInstaller as their arm9loaderhax.bin, it would speedup the process, as they wouldn't have to get luma 7.0.5 (a lot of users are in <7.0), set it up, then use the chainloader.

[Also this](https://github.com/Plailect/Guide/issues/1411), [and this](https://github.com/Plailect/Guide/pull/1421)

(added from another open issue)
Also, provide NTR FIRMs for flashing onto DS flashcarts so that you can flash SafeB9SInstaller onto your flashcart directly.

**Comment by d0k3** [comment]
Alright, willing to take a pull request for this. Screeninit on A9LH is somewhat of a pita, though, so don't expect this to be quick. Also, has to be 100% fail and foolproof.

If I get that pull request, I'll also fulfil https://github.com/d0k3/SafeB9SInstaller/issues/31 which would otherwise not warrant a release.

**Comment by angelsl** [comment]
> @jason0597: @angelsl you got the all clear

Right, well, I'll get on this after I finish Ultra Moon, if no one else does it..

**Comment by d0k3** [comment]
Okay, leaving this open for the time being, but this issue may be no more relevant. You can just use a GM9 script runner to speed up the installation process, and that will run perfectly from a ntrboot cart.

**Comment by jason0597** [comment]
GM9 on A9LH?

**Comment by angelsl** [comment]
Oh boy, I totally forgot about this.

I don't feel like there's really much point to this at this point, aside from completeness I guess...

**Comment by d0k3** [comment]
@angelsl - agreed. A9LH installations are somewhat of an edge case nowadays. For a console that is still on A9LH today, I doubt that anyone will ever bother updating to sighax. Add to that *that there is already workaround* for the remaining handful of A9LH users that still want to upgrade. And we also have ntrboot now. And, screeninit is not exactly trivial on these old A9LH payloads.

In short, I doubt it's worth it putting any work into this.

**Comment by d0k3** [comment]
Okay, screeninit will be coming, but not here. In face, no further features or improvements for this. We may fix critical bugs, tho.

Developement will continue here:
https://github.com/d0k3/OpenFirmInstaller/issues/3

More explanation: SafeB9SInstaller, at this point, is the same thing as OpenFirmInstaller, but with removed functionality (being able to install fastboot3DS in that case). There's just no point in updating both projects anymore.
