### ISSUE TITLE
Stuck on MicroSD Card 

### ISSUE THREAD

**Issue by Mavese85** [d0k3/SafeSigHaxInstaller#33]
Says "checking" and never goes past it ??

**Comment by LuisMayo** [comment]
@Mavese85 what was the problem? I have had this happening to me in two different systems using a lot of different SD Cards.

For reference, this has only happened to me using ctrboothax (my preferred method), using seedminer seemed fine for some reason?

**Comment by Joly0** [comment]
Hey guys, is there a solution to this problem? I wanted to revive my old 2ds xl which was previously running an old version of luma, b9s and safeb9sinstaller and am now stuck at the "MicroSD Card - checking...." step with no option to continue and no apparent reason why it stops there.

I even tried checking and reformatting the SD card and used other ones that are known good, but no chance. It's always stuck at that one step.

**Comment by urherenow** [comment]
Are you sure your card slot is good? If you tried multiple cards, I would think probably not.
