### ISSUE TITLE
sigHaxed FIRM was not installed!

### ISSUE THREAD

**Issue by malrogi101** [d0k3/SafeSigHaxInstaller#34]
Ive been following this guide [https://3ds.guide/installing-boot9strap-(homebrew-launcher)] word for word untill the 5th step. when I opened safe hax it told me:
sigHaxed FIRM was not installed!
how do i fix it?

**Comment by urherenow** [comment]
Ask in gbatemp. This isn't a forum.

**Comment by d0k3** [comment]
@urherenow is right. This is strictly for bug reports and feature requests. Even if you would ask for help here - this is missing information. SafeB9SInstaller actually tells you what went wrong. Reread the guide, and, if you still can't figure it out, ask elsewhere, actually providing the required info. Closing this now.
