### ISSUE TITLE
FIRM Backup Fail

### ISSUE THREAD

**Issue by JamesKeating86** [d0k3/SafeSigHaxInstaller#36]
Hello there,

firstly, thanks for all your work on this and I do hope you can help me.

I have been trying to get this to complete on my (old) 3ds xl all day.  I am on 11.2.0.35 (Eur).  During install it passes the first four checks (all green) then gets to "Backup status" - this shows 0% then immediately fails with the error "FIRM Backup fail".  I have been googling for answers but haven't come up with anything, can you advise at all?

Thanks,
James

**Comment by JamesKeating86** [comment]
So i got to the bottom of this through trial and error.  This is caused by using a 64GB Micro SDCard, i reran the whole process with a 16GB card on the same 3ds xl and it worked perfectly, hopefully this will help someone else.

James

**Comment by d0k3** [comment]
I can only add that the 3DS SD reader hardware is weird sometimes. There shouldn't be any trouble regardless of the size of your SD card (I got a 64GB one myself). I recommend checking the SD card for possible problems using h2testw.

**Comment by d0k3** [comment]
Oh well, why haven't I closed that already?
