### ISSUE TITLE
Keep booting into SafeB9SInstaller

### ISSUE THREAD

**Issue by EnbyAce** [d0k3/SafeSigHaxInstaller#37]
My friend followed 3ds.guide but at SafeB9SInstaller he got an error and now his 2DS will open SafeB9SInstalller each time he boots. Is there a way to fix that?

**Comment by piratesephiroth** [comment]
just put Luma3DS's boot.firm on the SD

**Comment by EnbyAce** [comment]
But he already entered the key combo and got an error, sooo... Is it safe then?

**Comment by piratesephiroth** [comment]
if the 3DS is booting into SafeB9S installer automatically, then boo9strap is installed already

**Comment by EnbyAce** [comment]
But the installation failed, I already made him sad because he thinks i broke his 2DS and I really don't want to make it worse.

**Comment by d0k3** [comment]
Aw come on, this is not a support forum. @KironDevCoder - you read teh instrcutions incorrectly. Just put the Luma `boot.firm` on the SD card. If you need more help, ask in some support place (GBAtemp / IRC / Discord).
