### ISSUE TITLE
SafeB9SInstaller error

### ISSUE THREAD

**Issue by HeroMines** [d0k3/SafeSigHaxInstaller#4]
Sighaxed Firm - file not found.

**Comment by Chy100** [comment]
Check that you have the correct files in your boot9strap folder. I had the same error and i found that my files was wrong.

The correct files in "boot9strap" folder are: 

boot9strap.firm
boot9strap.firm.sha
secret_sector.bin

**Comment by HeroMines** [comment]
Thanks. :-)
