### ISSUE TITLE
cannot compile with current devkitarm

### ISSUE THREAD

**Issue by MechanicalDragon0687** [d0k3/SafeSigHaxInstaller#40]
current dev environment cannot compile. 
looks to be missing some flags in the makefile

**Comment by d0k3** [comment]
Is this fixed by your pull request?

If it is, I'll look into it. But, as SafeB9SInstaller at this point is the exact same thing as OpenFirmInstaller, but with _removed_ functionality, you may also want to look into [OpenFirmInstaller](https://github.com/d0k3/OpenFirmInstaller).

**Comment by MechanicalDragon0687** [comment]
yes, and i believe that i pulled the makefile changes from OFI, in fact.

While i recognize OFI is the new product, sb9si is simpler and simple/less options = less chance for user failure.  Is there value added for OFI if installing b9s?

OFI also has the same partial a9lh uninstall issue #41 

In addition to the previous, the desired bootloader (for the same simplicity reasons) is currently b9s rather than fb3ds. Unfortunately, OFI not only advertises fb3ds on it's main readme page but prioritizes the fb3ds firm over b9s. I am not sure the issues tracker is the appropriate place for the discussion of fb3ds vs b9s, however.
