### ISSUE TITLE
does not properly remove a9lh during the a9lh uninstall stage

### ISSUE THREAD

**Issue by MechanicalDragon0687** [d0k3/SafeSigHaxInstaller#41]
removes part of the a9lh install but leaves the plaintext payload in firm1.
Needs reworking of the a9lh removal part of the app to properly remove it (rather than just lazily removing part of it)

see <https://github.com/AuroraWright/SafeA9LHInstaller/blob/d55a454b15ed2b3a47fa318327164e996713d43e/source/installer.c#L347> for an example of safe removal of both a9lh and the stage2 payload

**Comment by d0k3** [comment]
I'll look into it. This is fixed by your pull request, right?

**Comment by MechanicalDragon0687** [comment]
This is one of the things fixed by the pull request though the nature of the PR differs with solely fixing this.

The PR globally clears the stage 2 payload address regardless of a9lh install state in order to resolve previous a9lh style payload installs (regardless of current a9lh install state). if the goal is to solely fix future a9lh uninstalls, the PR will likely need to be reworked to only remove during the a9lh uninstall.
