### ISSUE TITLE
SafeB9SInstaller FAT 32 64 GB Micro SD Card Init. Failed on O3DS

### ISSUE THREAD

**Issue by Kuusetsu** [d0k3/SafeSigHaxInstaller#5]
When I attempted to use the installer, I kept getting a "Micro SD Card Init. Failed" error. I have a PNY 64 GB Micro SD Card formatted to FAT 32. I'm also using an O3DS. I also had to copy the payload to CTRNAND to use it, as the system kept ignoring the start_SafeB9SInstaller.bin file in my /luma/payloads folder.

**Comment by Slashin-it-up** [comment]
Redownload it.

**Comment by Kuusetsu** [comment]
I tried with a different card and it seems to have worked.

**Comment by Cottoneyes** [comment]
I've got this issue too, same situation except Luma does recognize my payload so I didn't to use CTRNAND like the OP. I don't have another SD card that I can use, so I need to fix this one. Have tried redownloading, didn't work.

**Comment by d0k3** [comment]
Do the same thing @RefractionGhoul did, use a different SD card. A small one is fine.

**Comment by Cottoneyes** [comment]
I'll have to go buy one, I suppose. What size would I need and what would I transfer over? Right now my 3ds files total 19gb including games.

**Comment by d0k3** [comment]
Any size, actually. 2GB is more than enough. You can also format the one you got anew.

**Comment by Cottoneyes** [comment]
Alright I found a 4gb SD card. For anyone reading this in future, make sure the new SD card is empty and then do the 3ds.guide updating to boot9strap steps on that card without transferring anything over from the old one.
