### ISSUE TITLE
Latest SafeB9SInstaller commit (nightly) generates a 0-byte SafeB9SInstaller.firm

### ISSUE THREAD

**Issue by MelonGx** [d0k3/SafeSigHaxInstaller#50]
As topic.
0.0.7 release version doesn't have this problem.

**Comment by d0k3** [comment]
Does this still happen? I think it should be fixed now.

**Comment by MelonGx** [comment]
I used d0k3.secretalgorithm.com to get nightly but it’s not working now so I can’t try it.

**Comment by d0k3** [comment]
@MelonGx - https://d0k3.secretalgorithm.com/ is back up. Can you try again?

**Comment by d0k3** [comment]
Closing, assuming it solved.

**Comment by hurda** [comment]
It was never fixed, unfortunately

The last good file that I could find was SafeB9SInstaller-20190111-223247.zip
![SafeB9SInstaller-20190111-223247 zip](https://github.com/d0k3/SafeB9SInstaller/assets/3539609/a0999495-63c6-4818-a634-a3da642e93b5)

Then there were a couple of new files in December of 2019 (and maybe earlier) which didn't come with a firm at all, e.g. SafeB9SInstaller-20191212-060705.zip to SafeB9SInstaller-20191214-183749.zip
![SafeB9SInstaller-20191212-060705 zip](https://github.com/d0k3/SafeB9SInstaller/assets/3539609/637f8fbd-0695-46c0-8045-25b023b4620f)

And the first bad file with the 0-byte-sized firm is SafeB9SInstaller-20200506-190039.zip
![SafeB9SInstaller-20200506-190039 zip](https://github.com/d0k3/SafeB9SInstaller/assets/3539609/8e08b69b-0f85-45a7-ad37-084efa648822)
And that is how it has been up to and including the most recent nightly SafeB9SInstaller-20230908-090136.zip

The Decrypt9WIP-files have the same issue from similar dates, but there wasn't any change in that program and it's officially deprecated, so it probably doesn't matter as the download from its github-release-page is "up-to-date" anyway.
But for the record:
last good Decrypt9WIP-20181124-120339.zip
no firm Decrypt9WIP-20191213-014023.zip
0 bytes firm Decrypt9WIP-20200423-162833.zip

**Comment by MelonGx** [comment]
Sorry it still exists on SafeB9SInstaller-20230913-090148.zip.
