### ISSUE TITLE
Running SafeB9SInstaller.bin built with latest version of devkitPro fails with FIRM crypto fail

### ISSUE THREAD

**Issue by nnn1590** [d0k3/SafeSigHaxInstaller#54]
I tried to build `SafeB9SInstaller.bin` with the latest version of devkitPro.
The build succeeded (except for 2xrsa) but when I run it, I get the error `Crypto Status - FIRM crypto fail`.

https://d0k3.secretalgorithm.com/SafeB9SInstaller/SafeB9SInstaller-20220819-221419.zip works for me, but I want to build it myself...!

Dockerfile: https://github.com/nnn1590/SafeB9SInstaller/blob/b276507883d0caa7345ad150fb23ce3d6f2a81e6/Dockerfile

Device: new3DS(11.16.0-49J)
BannerBomb3 and unSAFE_MODE used

Host OS: Ubuntu 20.04 LTS amd64

**Comment by Masamune3210** [comment]
I'm not sure a build that has the qualifier of "except for *" can really be considered a success

**Comment by nnn1590** [comment]
As far as I can see the [Makefile](https://github.com/d0k3/SafeB9SInstaller/blob/67c4eeaf1b9b19a883c639c52efaf68d3a60c272/Makefile), I thought that 2xrsa doesn't need to build `SafeB9SInstaller.bin`.
And `make` and `make binary` builds `SafeB9SInstaller.bin` without error.
(`make 2xrsa` and `make release` which needs 2xrsa will fails, but this issue is not about 2xrsa)
So I didn't mind.

**Comment by Masamune3210** [comment]
It might not be, I misremembered what it was for. Will have to wait for someone who knows more about what they are talking about to chime in. I do know that unless you have a way to flash through hardware, you might want to be careful compiling things like this, just in case something goes wrong and you end up with a brick

**Comment by urherenow** [comment]
Although I can’t build 2xrsa, I don’t have any issue building SB9Sinstaller with either make or make release. Besides warnings, it completes. Are you sure your whole toolchain is up to date, and you’ve tried from a fresh clone (or at least make clean before building)?

And how exactly are you trying to run it? On which system, which firmware, and has said system ever been hacked? The zip produced contains .3dsx, .bin, .dat, .firm, .nds, and launcher.dat. Too many options here and too little information…

**Comment by nnn1590** [comment]
I'm sure that my devkitPro is up-to-date. (`dkp-pacman -Syyu`ed)
I tried building with new Git checkout (without Docker) and above Dockerfile, but both result are same.

I will only use `SafeB9SInstaller.bin`.

```bash
# Non-Docker
cd "$(mktemp -d)"
git clone https://github.com/d0k3/SafeB9SInstaller.git --recursive .
make  # or "make release"
```
```bash
# Docker
wget https://raw.githubusercontent.com/nnn1590/SafeB9SInstaller/b276507883d0caa7345ad150fb23ce3d6f2a81e6/Dockerfile
docker build --tag "$USER/safeb9sinstaller" .
docker create --name tempcontainer "$USER/safeb9sinstaller"
docker cp tempcontainer:/SafeB9SInstaller/output/SafeB9SInstaller.bin .
docker rm tempcontainer
# Put SafeB9SInstaller.bin in the root of SD and boot 3DS (unSAFE_MODE installed).
# Then, boot the installer with [Proxy Settings] -> [Detailed Setup]
# However I get "Crypto Status - FIRM crypto fail".
```

**Comment by urherenow** [comment]
Dunno what all that docker stuff is, but that’s where you differ from me.

git clone —recursive…
make release

done 🤷‍♂️

although, haven’t you noticed that this hasn’t been updated since 2017? You should be using https://github.com/d0k3/OpenFirmInstaller and the guide should be updated (perhaps to include a mention of fb3ds as well).

**Comment by nnn1590** [comment]
> haven’t you noticed that this hasn’t been updated since 2017? 

Oh, I didn't notice😳
I built OpenFirmInstaller(.bin) and fastboot3DS (with a new RSA-2048 key) and successfully installed without any errors!
Thank you for the information!
