### ISSUE TITLE
In A9LH, SafeB9SInstaller.bin can't be booted as arm9loaderhax.bin

### ISSUE THREAD

**Issue by MelonGx** [d0k3/SafeSigHaxInstaller#6]
If loaded it as arm9loaderhax.bin, it would black screen forever until you forced shutting down the console.

This means we have to load this software as a payload of Luma or other CFW, but not directly boot it.

**Comment by MelonGx** [comment]
By the way, it also had a black screen as safehaxpayload.bin on a 9.1.0-20J N3DS.
It took over 5 retries to properly enter this software.

**Comment by d0k3** [comment]
arm9loaderhax_si.bin, and safehax being wonky is normal.

**Comment by MelonGx** [comment]
Oh thanks! This makes the A9LH -> B9S more quicker.
