### ISSUE TITLE
Question: is SafeB9SInstaller an Updater as well?

### ISSUE THREAD

**Issue by sora10pls** [d0k3/SafeSigHaxInstaller#7]
As of commit 3f501cfa, there's been FIRM entrypoint support.

I was just wondering if it'd function the same as the ARM9 payload SafeA9LHInstaller had; if run as .firm, would SafeB9SInstaller act as an Updater rather than an Installer? Obviously to install the latest versions of B9S should updates be pushed in the future.

**Comment by Cuphat** [comment]
The process to update would be the exact same as the initial install, wouldn't it?

**Comment by d0k3** [comment]
Yes, but keep in mind, this here is not a forum or discussion platform.
