### ISSUE TITLE
SigHaxed.firm!!??

### ISSUE THREAD

**Issue by Walvire** [d0k3/SafeSigHaxInstaller#8]
Okay, so this is how it went, I was loading up safehax to load up B9SInstaller. Once it did the check, it said exactly this:
SigHaxed FIRM was not installed!
Check lower screen for more info.

(<A> to continue)

SafeB9SInstaller v0.0.6
-----------------------------
https://github.com/d0k3/SafeB9SInstaller/
:
Now I am confused because I've spent 3 days trying to do this and now I decide to post this.
I don't know what to do at all. Please help me...

**Comment by d0k3** [comment]
You tried this for three days, and not once you followed the hint to consult @Plailect's [guide](https://3ds.guide), really? That hint is in the application, and it is in the readme -_-.
