### ISSUE TITLE
Menuhax

### ISSUE THREAD

**Issue by 7starsuperman** [d0k3/SafeSigHaxInstaller#9]
I'm trying to upgrade to B9S from menuhax + EmuNAND but whenever I go into homebrew and open SafeB9SInstaller I just get booted into the menuhax screen. Any ideas?

**Comment by d0k3** [comment]
Can't say much about entrypoints, refer to the guide. Your EmuNAND has most likely an FW version that's too high. Do it from SysNAND!

**Comment by 7starsuperman** [comment]
I was doing it from SysNAND on 9.2 but since menuhax is kind of unstable
some homebrew apps don't work like the latest version of decrypt9 (I had to
use the November 2016 release for it to work). Any other suggestions as to
what I should do? I'd like to move to b9s but I can't get the 3dsx to work.
Thanks
